version: "3"
services:
  web:
    image: mignon/test-python:demo
    container_name: web
    ports:
    - "4000:80"
    links:
    - redis
  
  redis:
    image: library/redis:latest
    container_name: redis
    ports:
    - "6379:6379"